services:
  # Backend API service
  - type: web
    name: recipe-calculator-api
    env: python
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y tesseract-ocr
      sudo apt-get install -y tesseract-ocr-dan
      pip install -r server/requirements.txt
    startCommand: cd server && uvicorn main:app --host 0.0.0.0 --port $PORT
      
  # Frontend static site
  - type: web
    name: recipe-calculator-web
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://recipe-calculator-api.onrender.com