services:
  # Backend API service
  - type: web
    name: recipe-calculator-api
    env: docker
    region: oregon
    
  # Frontend static site
  - type: web
    name: recipe-calculator-web
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://recipe-calculator-api.onrender.com