services:
  # Backend API service
  - type: web
    name: recipe-calculator-api
    env: python
    buildCommand: |
      # Install system dependencies including Tesseract and Danish language pack
      apt-get update && \
      apt-get install -y tesseract-ocr tesseract-ocr-dan libtesseract-dev
      pip install -r server/requirements.txt
    startCommand: cd server && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONPATH
        value: server
      - key: TESSDATA_PREFIX
        value: /usr/share/tesseract-ocr/4.00/tessdata
      
  # Frontend static site
  - type: web
    name: recipe-calculator-web
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://recipe-calculator-api.onrender.com